"""
LaBraM Tool Specification for NS-Copilot Tool Registry

This provides a GENERIC interface description for LaBraM (Large Brain Model).
The tool ONLY does feature extraction. All downstream logic
(classification, metrics, visualization) is generated by the LLM.
"""

from typing import Dict, Any, List
import numpy as np


# Tool Registry Entry
LABRAM_TOOL_SPEC = {
    "name": "decode_with_labram",
    "description": """
Extract features from EEG data using the pretrained LaBraM foundation model.

LaBraM (Large Brain Model) is a Neural Transformer pretrained on ~2,500 hours
of EEG data from 20+ datasets. It outputs 200-dimensional latent representations
that capture universal EEG patterns across tasks and subjects.

**When to use:**
- Data modality: Raw EEG signals (.set, .edf, .bdf)
- Channel system: Standard 10-20 (any subset, 1-128 channels)
- Task type: Any EEG classification, regression, or feature extraction
- Especially beneficial with limited training data (< 100 subjects)

**Input:**
- eeg_data: List of (n_channels, n_samples) arrays, one per subject
  Data should be in microvolts. Any sampling rate supported (auto-resampled to 200Hz).
- sfreq: Sampling frequency in Hz
- ch_names: List of channel names in standard 10-20 notation

**Output:**
- features: (n_subjects, 200) latent representations
  The Code Generator must handle all downstream analysis.
""",
    "input_spec": {
        "eeg_data": (
            "list of numpy arrays, each (n_channels, n_samples), raw EEG per subject. "
            "Any sampling rate supported (auto-resampled to 200Hz internally)."
        ),
        "sfreq": "float, sampling frequency in Hz",
        "ch_names": (
            "list of str, channel names in standard 10-20 notation "
            "(e.g., ['FP1', 'FP2', 'F3', 'F4', ...])"
        ),
        "max_seconds": (
            "float or None, max duration per subject in seconds (default: 16s max)"
        ),
        "pool_method": (
            "str, pooling method: 'mean' (default, mean of patch tokens) "
            "or 'cls' (CLS token)"
        ),
    },
    "output_spec": {
        "features": "numpy array (n_subjects, 200), latent features",
    },
    "constraints": {
        "data_modality": ["eeg", "raw_eeg", "eeglab_set", "edf", "bdf"],
        "min_channels": 1,
        "max_channels": 128,
        "recommended_channels": 19,
        "channel_system": "10-20",
        "target_sfreq": 200,
        "max_duration_seconds": 16,
        "requires_gpu": True,
    },
    "tags": [
        "feature_extraction", "foundation_model", "eeg",
        "pretrained", "transformer", "10-20",
    ],
}


def labram_extract_features(
    eeg_data: list,
    sfreq: float,
    ch_names: List[str],
    **kwargs,
) -> Dict[str, Any]:
    """
    Extract LaBraM features from EEG data.

    Args:
        eeg_data: List of (n_channels, n_samples) arrays per subject
        sfreq: Sampling frequency
        ch_names: Channel names in 10-20 notation

    Returns dict with 'features' key: (n_subjects, 200) numpy array.
    """
    from neuro_copilot.core.models.labram_wrapper import LaBraMDecoder

    checkpoint_path = kwargs.get('checkpoint_path', None)
    max_seconds = kwargs.get('max_seconds', None)
    pool_method = kwargs.get('pool_method', 'mean')

    decoder = LaBraMDecoder(checkpoint_path)
    features = decoder.extract_features_batch(
        eeg_data, sfreq, ch_names, max_seconds, pool_method
    )

    return {
        'features': features,
        'n_subjects': features.shape[0],
        'embed_dim': features.shape[1],
        'checkpoint_path': decoder.checkpoint_path,
    }
