"""
MtM Tool Specification for NS-Copilot Tool Registry

This provides a GENERIC interface description for MtM (Multi-task Masking).
The tool ONLY does feature extraction. All downstream logic
(classification, metrics, visualization) is generated by the LLM.
"""

from typing import Dict, Any
import numpy as np


# Tool Registry Entry
MTM_TOOL_SPEC = {
    "name": "decode_with_mtm",
    "description": """
Extract features from neural spike data using the pretrained MtM foundation model.

MtM (Multi-task Masking) uses an NDT1 encoder pretrained on IBL Neuropixels
recordings from mice with 8 diverse masking strategies. It outputs latent
representations that can be used with ANY downstream task.

**When to use:**
- Data modality: Spike times or binned spike counts
- Species: Mouse (primary), other species as fallback
- Recording type: High-density extracellular (e.g. Neuropixels)
- Task type: Any (classification, regression, feature extraction, clustering)
- Data volume: Especially beneficial with limited training data

**Input:**
- spike_data: (n_trials, n_time_bins, n_neurons) array of binned spike counts
  Bin size should be 20ms, trial window up to 2 seconds (100 bins max).
  The Code Generator must transform raw data to this format.

**Output:**
- features: (n_trials, hidden_dim) latent representations
  The Code Generator must handle all downstream analysis.
""",
    "input_spec": {
        "spike_data": (
            "numpy array (n_trials, n_time_bins, n_neurons) of binned spike "
            "counts. Bin size: 20ms. Max time bins: 100 (2s window)."
        ),
        "checkpoint_path": (
            "str or None, path to MtM checkpoint (auto-detected if None)"
        ),
        "pool_method": (
            "str, temporal pooling method: 'mean', 'max', or 'last' "
            "(default: 'mean')"
        ),
    },
    "output_spec": {
        "features": "numpy array (n_trials, hidden_dim), latent features",
    },
    "constraints": {
        "data_modality": ["spike_times", "binned_spikes"],
        "min_neurons": 5,
        "recommended_neurons": 30,
        "max_neurons": 668,
        "recommended_species": ["mouse"],
        "recommended_recording": ["neuropixels", "silicon_probe"],
        "bin_size_ms": 20,
        "max_time_bins": 100,
        "requires_gpu": True,
    },
    "tags": [
        "feature_extraction", "foundation_model", "spike",
        "pretrained", "mouse", "neuropixels",
    ],
}


def mtm_extract_features(
    spike_data: np.ndarray,
    **kwargs,
) -> Dict[str, Any]:
    """
    Extract MtM features from spike data.

    This function expects data ALREADY in MtM format:
    - spike_data: (n_trials, n_time_bins, n_neurons) array of spike counts

    Returns dict with 'features' key: (n_trials, hidden_dim) numpy array.
    """
    from neuro_copilot.core.models.mtm_wrapper import MTMDecoder
    import torch

    checkpoint_path = kwargs.get('checkpoint_path', None)
    pool_method = kwargs.get('pool_method', 'mean')

    decoder = MTMDecoder(checkpoint_path)
    spike_tensor = torch.FloatTensor(spike_data)
    features = decoder.extract_features(spike_tensor, pool_method=pool_method)

    return {
        'features': features,
        'n_trials': features.shape[0],
        'hidden_dim': features.shape[1],
        'checkpoint_path': decoder.checkpoint_path,
    }


# Export for Tool Registry
GENERIC_MTM_TOOL = {
    'mtm_decode': mtm_extract_features,
    'mtm_spec': MTM_TOOL_SPEC,
}
