"""
NDT3 Tool Specification for NS-Copilot Tool Registry

This provides a GENERIC interface description for NDT3.
The tool ONLY does feature extraction. All downstream logic
(classification, metrics, visualization) is generated by the LLM.
"""

from typing import Dict, Any
import numpy as np


# Tool Registry Entry
NDT3_TOOL_SPEC = {
    "name": "decode_with_ndt3",
    "description": """
Extract features from neural spike data using the pretrained NDT3 foundation model.

NDT3 is a 45M-parameter Transformer pretrained on 2000 hours of spike data.
It outputs latent representations that can be used with ANY downstream task.

**When to use:**
- Data modality: Spike times or binned spike counts
- Task type: Any (classification, regression, feature extraction, clustering, etc.)
- Data volume: Especially beneficial when sample size < 1 hour
- Task structure: Delayed response, working memory, motor planning

**Input:**
- spike_data: (n_trials, n_time_bins, n_neurons) array of binned spike counts
  The Code Generator must transform raw data to this format.

**Output:**
- features: (n_trials, hidden_dim) latent representations
  The Code Generator must handle all downstream analysis.
""",
    "input_spec": {
        "spike_data": "numpy array (n_trials, n_time_bins, n_neurons) of binned spike counts",
        "checkpoint_path": "str or None, path to NDT3 checkpoint (auto-detected if None)",
        "pool_method": "str, temporal pooling method: 'mean', 'max', or 'last' (default: 'mean')",
    },
    "output_spec": {
        "features": "numpy array (n_trials, hidden_dim), latent features",
    },
    "constraints": {
        "data_modality": ["spike_times", "binned_spikes"],
        "min_neurons": 10,
        "recommended_neurons": 32,
        "max_neurons": 320,
        "requires_gpu": True,
    },
    "tags": ["feature_extraction", "foundation_model", "spike", "pretrained"],
}


def ndt3_extract_features(
    spike_data: np.ndarray,
    **kwargs
) -> Dict[str, Any]:
    """
    Extract NDT3 features from spike data.

    This function expects data ALREADY in NDT3 format:
    - spike_data: (n_trials, n_time_bins, n_neurons) array of spike counts

    Returns dict with 'features' key: (n_trials, hidden_dim) numpy array.
    """
    from neuro_copilot.core.models.ndt3_wrapper import NDT3Decoder
    import torch

    checkpoint_path = kwargs.get('checkpoint_path', None)
    pool_method = kwargs.get('pool_method', 'mean')

    decoder = NDT3Decoder(checkpoint_path)
    spike_tensor = torch.FloatTensor(spike_data)
    features = decoder.extract_features(spike_tensor, pool_method=pool_method)

    return {
        'features': features,
        'n_trials': features.shape[0],
        'hidden_dim': features.shape[1],
        'checkpoint_path': decoder.checkpoint_path,
    }


# Export for Tool Registry
GENERIC_NDT3_TOOL = {
    'ndt3_decode': ndt3_extract_features,
    'ndt3_spec': NDT3_TOOL_SPEC,
}
