"""
POYO-1 Tool Specification for NS-Copilot Tool Registry

This provides a GENERIC interface description for POYO-1.
The tool ONLY does feature extraction. All downstream logic
(classification, metrics, visualization) is generated by the LLM.
"""

from typing import Dict, Any
import numpy as np


# Tool Registry Entry
POYO_TOOL_SPEC = {
    "name": "decode_with_poyo",
    "description": """
Extract features from neural spike data using the pretrained POYO-1 foundation model.

POYO-1 is a PerceiverIO-based model pretrained on 178 sessions (29,453 units)
from mouse and macaque recordings. It uses cross-attention to compress
individual spike tokens into a fixed set of latent representations.

**When to use:**
- Data modality: Spike times or binned spike counts
- Species: Mouse or macaque (primary), other species as fallback
- Recording type: Any extracellular electrophysiology (Neuropixels, Utah arrays, etc.)
- Task type: Any (classification, regression, feature extraction, clustering)
- Data volume: Especially beneficial with limited training data
- Unique strength: Handles variable numbers of neurons across sessions natively

**Input:**
- spike_data: (n_trials, n_time_bins, n_neurons) array of binned spike counts
  The Code Generator must transform raw data to this format.

**Output:**
- features: (n_trials, hidden_dim) latent representations (hidden_dim=128 for poyo_1)
  The Code Generator must handle all downstream analysis.
""",
    "input_spec": {
        "spike_data": (
            "numpy array (n_trials, n_time_bins, n_neurons) of binned spike "
            "counts. Any bin size is acceptable; default assumption is 20ms."
        ),
        "checkpoint_path": (
            "str or None, path to POYO checkpoint (auto-detected if None)"
        ),
        "pool_method": (
            "str, latent pooling method: 'mean', 'max', or 'last' "
            "(default: 'mean')"
        ),
    },
    "output_spec": {
        "features": "numpy array (n_trials, hidden_dim), latent features",
    },
    "constraints": {
        "data_modality": ["spike_times", "binned_spikes"],
        "min_neurons": 5,
        "recommended_neurons": 30,
        "max_neurons": 1000,
        "recommended_species": ["mouse", "macaque"],
        "recommended_recording": [
            "neuropixels", "utah_array", "silicon_probe",
        ],
        "requires_gpu": True,
    },
    "tags": [
        "feature_extraction", "foundation_model", "spike",
        "pretrained", "mouse", "macaque", "multi_species",
        "perceiver", "cross_attention",
    ],
}


def poyo_extract_features(
    spike_data: np.ndarray,
    **kwargs,
) -> Dict[str, Any]:
    """
    Extract POYO-1 features from spike data.

    This function expects data ALREADY in binned format:
    - spike_data: (n_trials, n_time_bins, n_neurons) array of spike counts

    Returns dict with 'features' key: (n_trials, hidden_dim) numpy array.
    """
    from neuro_copilot.core.models.poyo_wrapper import POYODecoder
    import torch

    checkpoint_path = kwargs.get('checkpoint_path', None)
    pool_method = kwargs.get('pool_method', 'mean')

    decoder = POYODecoder(checkpoint_path)
    spike_tensor = torch.FloatTensor(spike_data)
    features = decoder.extract_features(spike_tensor, pool_method=pool_method)

    return {
        'features': features,
        'n_trials': features.shape[0],
        'hidden_dim': features.shape[1],
        'checkpoint_path': decoder.checkpoint_path,
    }


# Export for Tool Registry
GENERIC_POYO_TOOL = {
    'poyo_decode': poyo_extract_features,
    'poyo_spec': POYO_TOOL_SPEC,
}
